package com.scube.crm.vo;

// Generated 5 Feb, 2015 10:16:28 AM by Hibernate Tools 4.0.0


import java.sql.Blob;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * JobSeekerProfile generated by hbm2java
 */

@Entity
@Table(name = "client_em_registration")
public class EmployerVO extends BasicEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private long id;

	private String firstName;

	private String lastName;

	private String emailAddress;

	private String confirmEmailAddress;

	private String contactNumber;

	private String mobileNumber;

	private String password;

	private String confirmPassword;

	private String companyName;

	private String companyType;

	private String industryType;

	private String webSite;

	private boolean isActive;

	private Boolean termsConditionsAgreed;

	private Blob companyLogo;

	private long deletedBy;

	private Date deletedDate;

	private boolean isDelete;

	private String address;

	private boolean updateStatus;
	
	private AdminLoginVO loginVO;
	
	private long assigned;
	
	private String status;
	
	//private boolean migrationStatus;



	/*private List<EmployerProfileVO> employerProfileVO;
	private List<EmployerLoginVO> employerLoginVO;*/

	
	

	@Id
	@GeneratedValue
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	/**
	 * @return the firstName
	 */
	@Column(name = "first_Name")
	public String getFirstName() {
		return this.firstName;
	}

	/**
	 * @param firstName
	 *            the firstName to set
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/**
	 * @return the lastName
	 */
	@Column(name = "last_Name")
	public String getLastName() {
		return this.lastName;
	}

	/**
	 * @param lastName
	 *            the lastName to set
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	/**
	 * @return the emailAddress
	 */
	@Column(name = "email_Id")
	public String getEmailAddress() {
		return this.emailAddress;
	}

	/**
	 * @param emailAddress
	 *            the emailAddress to set
	 */
	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	/**
	 * @return the confirmEmailAddress
	 */
	@Column(name = "con_Email_Id")
	public String getConfirmEmailAddress() {
		return this.confirmEmailAddress;
	}

	/**
	 * @param confirmEmailAddress
	 *            the confirmEmailAddress to set
	 */
	public void setConfirmEmailAddress(String confirmEmailAddress) {
		this.confirmEmailAddress = confirmEmailAddress;
	}

	/**
	 * @return the contactNumber
	 */
	@Column(name = "contact_Number")
	public String getContactNumber() {
		return this.contactNumber;
	}

	/**
	 * @param contactNumber
	 *            the contactNumber to set
	 */
	public void setContactNumber(String contactNumber) {
		this.contactNumber = contactNumber;
	}

	/**
	 * @return the mobileNumber
	 */
	@Column(name = "mobile_Number")
	public String getMobileNumber() {
		return this.mobileNumber;
	}

	/**
	 * @param mobileNumber
	 *            the mobileNumber to set
	 */
	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	/**
	 * @return the password
	 */
	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	/**
	 * @param password
	 *            the password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * @return the confirmPassword
	 */
	@Column(name = "con_Password")
	public String getConfirmPassword() {
		return this.confirmPassword;
	}

	/**
	 * @param confirmPassword
	 *            the confirmPassword to set
	 */
	public void setConfirmPassword(String confirmPassword) {
		this.confirmPassword = confirmPassword;
	}

	/**
	 * @return the companyName
	 */
	@Column(name = "company_Name")
	public String getCompanyName() {
		return this.companyName;
	}

	/**
	 * @param companyName
	 *            the companyName to set
	 */
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	/**
	 * @return the companyType
	 */
	@Column(name = "company_Type")
	public String getCompanyType() {
		return this.companyType;
	}

	/**
	 * @param companyType
	 *            the companyType to set
	 */
	public void setCompanyType(String companyType) {
		this.companyType = companyType;
	}

	/**
	 * @return the industryType
	 */
	@Column(name = "industry_Type")
	public String getIndustryType() {
		return this.industryType;
	}

	/**
	 * @param industryType
	 *            the industryType to set
	 */
	public void setIndustryType(String industryType) {
		this.industryType = industryType;
	}

	/**
	 * @return the webSite
	 */
	@Column(name = "website")
	public String getWebSite() {
		return this.webSite;
	}

	/**
	 * @param webSite
	 *            the webSite to set
	 */
	public void setWebSite(String webSite) {
		this.webSite = webSite;
	}

	

	/**
	 * @return the termsConditionsAgreed
	 */
	public Boolean getTermsConditionsAgreed() {
		return this.termsConditionsAgreed;
	}

	/**
	 * @param termsConditionsAgreed
	 *            the termsConditionsAgreed to set
	 */
	public void setTermsConditionsAgreed(Boolean termsConditionsAgreed) {
		this.termsConditionsAgreed = termsConditionsAgreed;
	}

	/**
	 * @return the companyLogo
	 */
	public Blob getCompanyLogo() {
		return this.companyLogo;
	}

	/**
	 * @param companyLogo
	 *            the companyLogo to set
	 */
	public void setCompanyLogo(Blob companyLogo) {
		this.companyLogo = companyLogo;
	}

	
	public Date getDeletedDate() {
		return this.deletedDate;
	}

	/**
	 * @param deletedDate
	 *            the deletedDate to set
	 */
	public void setDeletedDate(Date deletedDate) {
		this.deletedDate = deletedDate;
	}

	/**
	 * @return the deletedBy
	 */
	public long getDeletedBy() {
		return this.deletedBy;
	}

	/**
	 * @param deletedBy
	 *            the deletedBy to set
	 */
	public void setDeletedBy(long deletedBy) {
		this.deletedBy = deletedBy;
	}

	/**
	 * @return the address
	 */
	@Column(name="address")
	public String getAddress() {
		return address;
	}

	/**
	 * @param address the address to set
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * @return the updateStatus
	 */
	@Column(name="update_status")
	public boolean isUpdateStatus() {
		return updateStatus;
	}

	/**
	 * @param updateStatus the updateStatus to set
	 */
	public void setUpdateStatus(boolean updateStatus) {
		this.updateStatus = updateStatus;
	}

	/**
	 * @return the loginVO
	 */
	@ManyToOne
	@JoinColumn(name="adminId")
	public AdminLoginVO getLoginVO() {
		return loginVO;
	}

	/**
	 * @param loginVO the loginVO to set
	 */
	public void setLoginVO(AdminLoginVO loginVO) {
		this.loginVO = loginVO;
	}


	/**
	 * @return the isActive
	 */
	@Column(name="isActive")
	public boolean getIsActive() {
		return isActive;
	}

	/**
	 * @param isActive the isActive to set
	 */
	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	/**
	 * @return the isDelete
	 */
	@Column(name="isDelete")
	public boolean getIsDelete() {
		return isDelete;
	}

	/**
	 * @param isDelete the isDelete to set
	 */
	public void setIsDelete(boolean isDelete) {
		this.isDelete = isDelete;
	}

	/**
	 * @return the assigned
	 */
	@Column(name="assigned_to")
	public long getAssigned() {
		return assigned;
	}

	/**
	 * @param assigned the assigned to set
	 */
	public void setAssigned(long assigned) {
		this.assigned = assigned;
	}

	/**
	 * @return the status
	 */
	@Column(name="status")
	public String getStatus() {
		return status;
	}

	/**
	 * @param status the status to set
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * @return the migrationStatus
	 */
	//@Column(name="migration")
	//public boolean isMigrationStatus() {
		//return migrationStatus;
	//}

	/**
	 * @param migrationStatus the migrationStatus to set
	 */
	//public void setMigrationStatus(boolean migrationStatus) {
	//	this.migrationStatus = migrationStatus;
	//}
	
	
	
}
